import type { Metadata } from "next"
import { Inter, Roboto, Montserrat } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import localFont from "next/font/local"

const roboto = Roboto({
  variable: "--paragraph",
  weight: "400",
  subsets: ["latin"],
})

const sakkalMajala = localFont({
  src: "../../public/fonts/sakkal-majalla-bold.ttf",
  variable: "--heading",
  display: "swap",
  weight: "600",
})

export const metadata: Metadata = {
  title: "Cosmostrategy Homepage",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${roboto.variable} ${sakkalMajala.variable}`,
          "antialiased grainy font-sans min-h-screen w-screen relative overflow-x-hidden"
        )}
      >
        {children}
      </body>
    </html>
  )
}
